### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Doppie23** [Doppie23/WieBot#4]
404 soms bij reddit posts

**Comment by Doppie23** [comment]
Traceback (most recent call last):
  File "C:\Users\Daniël\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\tree.py", line 1240, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\Daniël\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 876, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\Daniël\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 869, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'shitpost' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
